import type { Operation, Service } from '@/lib/types';

export const initialServices: Service[] = [
  {
    name: 'checkout-api',
    namespace: 'production',
    current: 12,
    desired: 12,
    min: 4,
    max: 40,
    trigger: 'CPU · 61%',
    triggerType: 'manual',
    owner: 'Native HPA',
    latency: '1.8s',
    state: 'Stable',
  },
  {
    name: 'events-worker',
    namespace: 'production',
    current: 18,
    desired: 24,
    min: 2,
    max: 80,
    trigger: 'SQS · 8.2k messages',
    triggerType: 'aws-sqs',
    owner: 'Scaler',
    latency: '2.4s',
    state: 'Scaling',
  },
  {
    name: 'recommendations',
    namespace: 'production',
    current: 8,
    desired: 8,
    min: 3,
    max: 24,
    trigger: 'RPS · 1.4k',
    triggerType: 'manual',
    owner: 'Native HPA',
    latency: '1.2s',
    state: 'Stable',
  },
  {
    name: 'image-resizer',
    namespace: 'production',
    current: 4,
    desired: 8,
    min: 1,
    max: 20,
    trigger: 'S3 · uploads bucket',
    triggerType: 'aws-s3-event',
    owner: 'Scaler',
    latency: '3.1s',
    state: 'Scaling',
  },
  {
    name: 'fraud-alerts',
    namespace: 'production',
    current: 3,
    desired: 3,
    min: 2,
    max: 20,
    trigger: 'CW Alarm · backlog-high',
    triggerType: 'aws-cloudwatch-alarm',
    owner: 'Scaler',
    latency: '1.6s',
    state: 'Stable',
  },
  {
    name: 'ingest-pipeline',
    namespace: 'jobs',
    current: 6,
    desired: 6,
    min: 2,
    max: 40,
    trigger: 'CloudWatch · DynamoDB WCU',
    triggerType: 'aws-cloudwatch-metric',
    owner: 'Scaler',
    latency: '2.0s',
    state: 'Stable',
  },
  {
    name: 'pdf-renderer',
    namespace: 'jobs',
    current: 0,
    desired: 0,
    min: 0,
    max: 30,
    trigger: 'Schedule · 23:30',
    triggerType: 'aws-eventbridge-schedule',
    owner: 'Scaler',
    latency: '—',
    state: 'Paused',
  },
];

export const initialOperations: Operation[] = [
  {
    id: 'op-0144',
    workload: 'image-resizer',
    namespace: 'production',
    kind: 'Scale',
    from: 4,
    to: 8,
    status: 'Running',
    elapsedSeconds: 3,
    timeoutSeconds: 15,
    actor: 'S3 event burst',
    retentionDays: 14,
    editable: false,
    reversible: false,
  },
  {
    id: 'op-0142',
    workload: 'events-worker',
    namespace: 'production',
    kind: 'Scale',
    from: 18,
    to: 24,
    status: 'Running',
    elapsedSeconds: 7,
    timeoutSeconds: 30,
    actor: 'SQS policy',
    retentionDays: 30,
    editable: false,
    reversible: false,
  },
  {
    id: 'op-0141',
    workload: 'pdf-renderer',
    namespace: 'jobs',
    kind: 'Scale',
    from: 0,
    to: 8,
    status: 'Succeeded',
    elapsedSeconds: 3,
    timeoutSeconds: 10,
    actor: 'AM',
    retentionDays: 90,
    editable: false,
    reversible: true,
  },
  {
    id: 'op-0140',
    workload: 'events-worker',
    namespace: 'production',
    kind: 'Scale',
    from: 18,
    to: 36,
    status: 'Timed out',
    elapsedSeconds: 10,
    timeoutSeconds: 10,
    actor: 'Schedule',
    retentionDays: 14,
    editable: false,
    reversible: false,
    critical: true,
    criticalReasons: ['SCALE_UP_TIMED_OUT'],
    notificationStatus: 'Sent',
  },
  {
    id: 'op-0139',
    workload: 'pdf-renderer',
    namespace: 'jobs',
    kind: 'Schedule',
    from: 8,
    to: 0,
    status: 'Scheduled',
    elapsedSeconds: 0,
    timeoutSeconds: 10,
    actor: 'Schedule · 23:30',
    retentionDays: 30,
    editable: true,
    reversible: false,
  },
];

export const nav = [
  'Overview',
  'Definitions',
  'Workloads',
  'Schedules',
  'Operations',
  'Connections',
];
